services:
  tg-bot:
    build: .
    container_name: tg-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/Samara
    volumes:
      - .:/app
    env_file:
      - .env
    command: python tg.py
